#!/usr/bin/env python3

import requests
import re
import subprocess
import netifaces
import dns.resolver
import time
from datetime import datetime
import argparse
import sys

# Script parameters
ipv6_prefix_length = "/64"

def verify_ipv4(address):
    ipv4_pattern = re.compile(r'^(\d{1,3}\.){3}\d{1,3}$')
    try:
        if ipv4_pattern.match(address) and all(0 <= int(octet) <= 255 for octet in address.split('.')):
            return address
    except:
        return None
    return None

def verify_ipv6(address):
    ipv6_pattern = re.compile(r'^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$')
    try:
        if ipv6_pattern.match(address):
            return address
    except:
        return None
    return None

def get_host_ipv4():
    ip = None

    if ip is None:
        try:
            ip = verify_ipv4( requests.get('https://api.ipify.org', timeout=5).text.strip() )
        except:
            ip = None

    if ip is None:
        try:
            ip = verify_ipv4( requests.get('https://checkip.amazonaws.com', timeout=5).text.strip() )
        except:
            ip = None

    if ip is None:
        try: 
            result = subprocess.run('curl -4 https://ifconfig.me', capture_output=True, text=True, shell=True)
            ip = verify_ipv4( result.stdout )
        except:
            ip = None

    if ip is None:
        try:
            result = subprocess.run('curl -4 https://api.ipify.org', capture_output=True, text=True, shell=True)
            ip = verify_ipv4( result.stdout )
        except:
            ip = None

    return ip

def get_host_ipv6(network_interface_name):
    ip = None

    if ip is None:
        try:
            if network_interface_name not in netifaces.interfaces():
                ip = None
            else:
                addrs = netifaces.ifaddresses(network_interface_name)
                if netifaces.AF_INET6 in addrs:
                    for ipv6_info in addrs[netifaces.AF_INET6]:
                        ipv6 = ipv6_info.get('addr')
                        
                        # Ensuring global scope and not a link-local address (starting with fe80)
                        if ipv6.startswith('2') or ipv6.startswith('3'): # Global unicast addresses start with 2 or 3
                            ip = verify_ipv6( ipv6 )

        except:
            ip = None

    if ip is None:
        try:
            ip = verify_ipv6( requests.get('https://ifconfig.me', timeout=5).text.strip() )
        except:
            ip = None

    if ip is None:
        try: 
            result = subprocess.run('curl -6 https://ifconfig.me', capture_output=True, text=True, shell=True)
            ip = verify_ipv6( result.stdout )
        except:
            ip = None

    return ip

def get_domain_ipv4(domain):
    ip = None

    if ip is None:
        try: 
            command = f"dig A @8.8.8.8 +short {domain}"
            result = subprocess.run(command, capture_output=True, text=True, shell=True)
            ip = result.stdout.split("\n")
            ip = verify_ipv4( ip[0] )
        except:
            ip = None

    if ip is None:
        try:
            resolver = dns.resolver.Resolver()
            resolver.nameservers = ['8.8.8.8']
            result = resolver.resolve(domain, 'A')
            for ipval in result:
                ip = verify_ipv4( ipval.to_text().strip() )
        except:
            ip = None

    return ip

def get_domain_ipv6(domain):
    ip = None

    if ip is None:
        try: 
            command = f"dig AAAA @2001:4860:4860::8888 +short {domain}"
            result = subprocess.run(command, capture_output=True, text=True, shell=True)
            ip = result.stdout.split("\n")
            ip = verify_ipv6( ip[0] )
        except:
            ip = None

    if ip is None:
        try:
            resolver = dns.resolver.Resolver()
            resolver.nameservers = ['2001:4860:4860::8888']
            result = resolver.resolve(domain, 'AAAA')
            for ipval in result:
                ip = verify_ipv6( ipval.to_text().strip() )
        except:
            ip = None

    return ip


def main():

    # Parse command line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("--domain","-d", type=str)     # Domain name
    parser.add_argument("--token","-t", type=str)      # Dynv6 authentication token
    parser.add_argument("--logfile","-l", type=str)    # Logfile
    parser.add_argument("--nic","-n", type=str)        # network_interface_name
    args = parser.parse_args()

    domain = args.domain
    if domain is None:
        sys.stderr.write(f"ERROR: Domain name not given.\n")
        sys.exit(1)

    token = args.token
    if token is None:
        sys.stderr.write(f"ERROR: Token not given.\n")
        sys.exit(1)

    logfile = args.logfile

    nic = args.nic
    if nic is None:
        nic = 'enp4s0'

    # Try to get host and domain IP addresses, repeat 6 time on failure, total of 2:30 minutes
    # DSL takes 2 minutes to synchronize
    for i in range(0,6):

        ipv4_host = get_host_ipv4()
        ipv6_host = get_host_ipv6(nic)
        ipv4_domain = get_domain_ipv4(domain)
        ipv6_domain = get_domain_ipv6(domain)

        if ipv4_host is not None and ipv6_host is not None and ipv4_domain is not None and ipv6_domain is not None:
            break
        elif i < 5:
            time.sleep(30)
    
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    # Write an error message to the log if an address could not be resolved
    if ipv4_host is None or ipv6_host is None or ipv4_domain is None or ipv6_domain is None:
        strg = ""
        if ipv4_host is None:
            strg = strg + "IPv4 Host, "
        if ipv6_host is None:
            strg = strg + "IPv6 Host, "
        if ipv4_domain is None:
            strg = strg + "IPv4 Domain, "
        if ipv6_domain is None:
            strg = strg + "IPv6 Domain, "
        if logfile is not None:
            with open(logfile, 'a') as file:
                file.write(f"{now} ERR: Could not resolve {strg[:-2]}\n")

    # Update IPv4 address
    if (ipv4_host and ipv4_domain and ipv4_host != ipv4_domain) or (ipv4_host and ipv4_domain is None):
        try:
            result = requests.get(f"https://dynv6.com/api/update?hostname={domain}&token={token}&ipv4={ipv4_host}", timeout=70).text
        except:
            result = 'failed'

        now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        if logfile is not None:
            with open(logfile, 'a') as file:
                if result:
                    file.write(f"{now} v4 {ipv4_domain} >>> {ipv4_host} ({result})\n")
                else:
                    file.write(f"{now} v4 {ipv4_domain} >>> {ipv4_host}\n")

    # Update IPv6 address
    if (ipv6_host and ipv6_domain and ipv6_host != ipv6_domain) or (ipv6_host and ipv6_domain is None):
        try:
            result = requests.get(f'https://dynv6.com/api/update?hostname={domain}&token={token}&ipv6={ipv6_host+ipv6_prefix_length}', timeout=70).text
        except:
            result = 'failed'

        now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        if logfile is not None:
            with open(logfile, 'a') as file:
                if result:
                    file.write(f"{now} v6 {ipv6_domain} >>> {ipv6_host} ({result})\n")
                else:
                    file.write(f"{now} v6 {ipv6_domain} >>> {ipv6_host}\n")


if __name__ == "__main__":
    main()
